#development:
#  adapter: async
#
#test:
#  adapter: test
#
#production:
#  adapter: <%= ENV['CABLE_ADAPTER'] || 'async' %>
production:
  url: redis://localhost:6379

local: &local
  url: redis://localhost:6379

development: *local
test: *local